#! /bin/bash

cd ~/Documents/VPN
action=$(yad --width 500 --title "Connect to IranSec VPN" \
    --window-icon=iransec.png \
    --licon=iransec.png \
    --image=iransec.png \
    --button="US1:2" \
    --button="US2:3" \
    --button="UK1:4" \
    --button="gtk-close:1" \
    --text "Select one of the servers:" \
    --mouse
    )
ret=$?

[[ $ret -eq 1 ]] && exit 0

case $ret in 
    2)
        sudo openvpn --config UK1-IST-V1-Linux.ovpn | 
        yad --text-info --title "Connecting to IranSec VPN (UK1 - v1)" --width 600 --height 300 \
        --text "Here is the log file of IranSec VPN. In case of any problem please send it to us to investigate." \
        --licon=iransec.png \
        --button="Disconnect:bash -c 'sudo pkill openvpn' && exit 0" \
        --button="gtk-close:0"
        ;;
    3)
        sudo openvpn --config US1-IST-V1-Linux.ovpn | 
        yad --text-info --title "Connecting to IranSec VPN (UK1 - v1)" --width 600 --height 300 \
        --text "Here is the log file of IranSec VPN. In case of any problem please send it to us to investigate." \
        --licon=iransec.png \
        --button="Disconnect:bash -c 'sudo pkill openvpn' && exit 0" \
        --button="gtk-close:0"
        ;;
    4)
        sudo openvpn --config US2-IST-V1-Linux.ovpn | 
        yad --text-info --title "Connecting to IranSec VPN (UK1 - v1)" --width 600 --height 300 \
        --text "Here is the log file of IranSec VPN. In case of any problem please send it to us to investigate." \
        --licon=iransec.png \
        --button="Disconnect:bash -c 'sudo pkill openvpn' && exit 0" \
        --button="gtk-close:0"        ;;
    *)
        printf "\n\n\nJust press 1, 2, or 3. I can't understand other charachters!"
        sleep 1
esac

cd /
#generated by http://patorjk.com/software/taag/#p=testall&h=0&v=0&c=bash&f=Isometric1&t=IranSec
iransec[0]=" ###                       #####                "
iransec[1]="  #  #####    ##   #    # #     # ######  ####  "
iransec[2]="  #  #    #  #  #  ##   # #       #      #    # "
iransec[3]="  #  #    # #    # # #  #  #####  #####  #      "
iransec[4]="  #  #####  ###### #  # #       # #      #      "
iransec[5]="  #  #   #  #    # #   ## #     # #      #    # "
iransec[6]=" ### #    # #    # #    #  #####  ######  ####  "
iransec[7]=" A    S h i e l d    f o r    D e f e n d e r s "
iransec[8]="              support@iransec.org               "
clear
#for aligning it center and randomize its color for each run || read more: http://www.linuxquestions.org/questions/linux-newbie-8/bash-script-center-text-on-screen-4175417274/ and http://www.commandlinefu.com/commands/view/12548/generate-a-random-text-color-in-bash
printf "\e[3$(( $RANDOM * 6 / 32767 + 1 ))m"
y=$[($(tput cols)-${#iransec[0]})/2]
x=$[($(tput lines)-${#iransec[@]})/2]
for i in "${!iransec[@]}"
    do
        tput cup $x $y
        if [ $i = 7 ]; then
            printf "\033[1m\e[100m\e[39m ${iransec[$i]} \033[0m"
        else
            printf "\e[3$(( $RANDOM * $i / 32767 + 1 ))m ${iransec[$i]} \033[0m"
        fi
        x=$[x+1]
    done
    
echo ""
echo ""
echo ""
echo ""

eval exec $cmd
